swagger: '2.0'
info:
  description: Publish and manage timestamped key-value-pair data.
  version: '1'
  title: SystemLink Tag Service
  contact:
    name: National Instruments
    url: 'https://www.ni.com/systemlink'
    email: support@ni.com
basePath: /nitag
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apiKeyAuth:
    type: apiKey
    name: x-ni-api-key
    in: header
  basicAuth:
    type: basic
security:
  - apiKeyAuth: []
  - basicAuth: []

responses:
  Unauthorized:
    description: Not authorized
    headers:
      WWW_Authenticate:
        description: Information for how to authenticate (sent only from SystemLink Server).
        type: string
  Error:
    description: Error (sent only from SystemLink Server)
    schema:
      description: Error response
      title: ErrorResponse
      type: object
      properties:
        error:
          $ref: '#/definitions/Error'
  GetTagsWithValuesResponse:
    description: List of tags, including their current and aggregate values
    schema:
      properties:
        totalCount:
          description: Total number of tags which match a given query
          type: integer
        tagsWithValues:
          description: List of tags with their current and aggregate values
          type: array
          items:
            $ref: '#/definitions/TagWithValue'
  GetTagsResponse:
    description: List of tags, excluding current and aggregate values
    schema:
      properties:
        totalCount:
          type: integer
          description: Total number of tags which match a given query
        tags:
          description: List of tags
          type: array
          items:
            $ref: '#/definitions/Tag'
  GetSubscriptionUpdatesResponse:
    description: List of subscription updates
    schema:
      properties:
        subscriptionUpdates:
          description: Subscription updates
          type: array
          items:
            $ref: '#/definitions/SubscriptionUpdate'
        invalidSubscriptionIds:
          description: List of invalid subscription IDs
          type: array
          items:
            type: string

paths:
  /v2/subscriptions:
    post:
      tags:
        - subscriptions
      summary: Create a subscription
      description: Create a subscription for a list of tags to get notifications when the tags change.
      operationId: CreateSubscription
      parameters:
        - in: body
          name: subscription
          description: The subscription to create
          schema:
            $ref: '#/definitions/Subscription'
          required: false
      responses:
        200:
          description: Success
          schema:
            description: Response for creating a subscription
            type: object
            title: Create Subscription Response
            properties:
              subscriptionId:
                type: string
              nonexistentTags:
                description: List of tags which did not exist
                type: array
                items:
                  type: string
              alias:
                type: string
                description: Name of the subscription
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
    get:
      tags:
        - subscriptions
      summary: Get active subscription IDs
      description: Get a list of all active subscription IDs
      operationId: GetSubscriptions
      parameters: []
      responses:
        200:
          description: Success
          schema:
            description: Get subscriptions response
            type: object
            title: Get Subscriptions Response
            properties:
              subscriptionIds:
                description: List of all the active subscription IDs
                type: array
                items:
                  type: string
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v2/subscriptions/{id}:
    parameters:
    - in: path
      name: id
      description: Subscription ID
      type: string
      required: true
    get:
      tags:
        - subscriptions
      summary: Get a subscription
      description: Get a subscription's metadata
      operationId: GetSubscription
      responses:
        200:
          schema:
            $ref: '#/definitions/Subscription'
          description: Success
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Subscription with the given ID was not found
        default:
          $ref: '#/responses/Error'
    delete:
      tags:
        - subscriptions
      summary: Delete a subscription
      description: Delete a specific subscription.
      operationId: DeleteSubscription
      responses:
        204:
          description: Successfully deleted
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Subscription with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/subscriptions/{id}/heartbeat:
    put:
      tags:
        - subscriptions
      summary: Update the heartbeat timer for a subscription
      description: Update the heartbeat timer for the specified subscription
      operationId: UpdateSubscriptionHeartbeat
      parameters:
        - in: path
          name: id
          description: The subscription ID
          type: string
          required: true
      responses:
        200:
          description: Success
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Subscription with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/subscriptions/{id}/values/current:
    get:
      tags:
        - subscriptions
      summary: Get the current values for the tags in a subscription
      description: Get the current values for tags in the subscription (either all or changed only based on a query parameter).
      operationId: GetSubscriptionTagValues
      parameters:
        - in: path
          name: id
          description: Subscription ID
          type: string
          required: true
      responses:
        200:
          schema:
            $ref: '#/responses/GetSubscriptionUpdatesResponse'
          description: Success
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v1/tags-rpc/subscriptions/heartbeat:
    post:
        tags:
          - subscriptions
        summary: Update the heartbeat timer of multiple subscriptions
        description: Updates the heartbeat timers of multiple subscriptions. Note that this route is deprecated.
        operationId: RpcUpdateSubscriptionHeartbeats
        parameters:
          - in: body
            name: subscriptionIds
            description: IDs of the subscriptions whose heartbeat timers should be updated
            required: false
            schema:
              type: array
              items:
                type: string
        responses:
          200:
            description: Success
            schema:
              description: Update subscriptions heartbeat response
              type: object
              title: Update Subscriptions Heartbeat Response
              properties:
                invalidSubscriptionIds:
                  description: List of invalid subscription IDs
                  type: array
                  items:
                    type: string
          401:
            $ref: '#/responses/Unauthorized'
          default:
            $ref: '#/responses/Error'
  /v2/refresh-subscriptions:
    post:
      tags:
        - subscriptions
      summary: Update the heartbeat timer of multiple subscriptions (SystemLink Server only)
      description: Updates the heartbeat timers of multiple subscriptions
      operationId: UpdateSubscriptionHeartbeats
      parameters:
        - in: body
          name: subscriptionIds
          description: IDs of the subscriptions whose heartbeat timers should be updated
          required: false
          schema:
            type: object
            properties:
              subscriptionIds:
                type: array
                items:
                  type: string
      responses:
        200:
          description: Success
          schema:
            description: The update subscriptions heartbeat response
            type: object
            title: Update Subscriptions Heartbeat Response
            properties:
              invalidSubscriptionIds:
                description: List of invalid subscription IDs
                type: array
                items:
                  type: string
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v1/tags-rpc/subscriptions/query-values:
    post:
      tags:
      - subscriptions
      summary: Get the current values for the tags from multiple subscriptions
      description: Get the current values for all tags in multiple subscriptions. Note that this route is deprecated.
      operationId: RpcGetSubscriptionsTagValues
      parameters:
        - in: body
          name: subscriptionIds
          description: Subscription ids
          schema:
            type: array
            items:
              type: string
          required: false
      responses:
        200:
          description: Success
          schema:
            $ref: '#/responses/GetSubscriptionUpdatesResponse'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Subscription with the given ID was not found
  /v2/query-subscription-values:
    post:
      tags:
        - subscriptions
      summary: Get the current values for the tags from multiple subscriptions (SystemLink Server Only)
      description: Get the current values for all tags in multiple subscriptions
      operationId: GetSubscriptionsTagValues
      parameters:
        - in: body
          name: subscriptionIds
          required: false
          schema:
            type: object
            properties:
              subscriptionIds:
                type: array
                items:
                  type: string
      responses:
        200:
          description: Success
          schema:
            $ref: '#/responses/GetSubscriptionUpdatesResponse'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Subscription with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v1/tags-rpc/subscriptions/delete:
    post:
      tags:
        - subscriptions
      summary: Delete multiple subscriptions
      description: Delete one or more subscriptions based on the request body. Note that this route is deprecated.
      operationId: RpcDeleteSubscriptions
      parameters:
        - in: body
          name: subscriptionIds
          schema:
            type: array
            items:
              type: string
          required: false
      responses:
        200:
          description: Success
          schema:
            description: Response for deleting subscriptions
            type: object
            title: Delete Subscriptions Response
            properties:
              invalidSubscriptionIds:
                description: List of invalid subscription IDs
                type: array
                items:
                  type: string
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v2/delete-subscriptions:
    post:
      tags:
        - subscriptions
      summary: Delete multiple subscriptions
      description: Delete one or more subscriptions based on the request body.
      operationId: DeleteSubscriptions
      parameters:
        - in: body
          name: subscriptionIds
          required: false
          schema:
            type: object
            properties:
              subscriptionIds:
                type: array
                items:
                  type: string
      responses:
        200:
          description: Success
          schema:
            description: Response for deleting subscriptions
            type: object
            title: Delete Subscriptions Response
            properties:
              invalidSubscriptionIds:
                description: List of invalid subscription IDs
                type: array
                items:
                  type: string
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v2/selections:
    post:
      tags:
        - selections
      summary: Create a selection
      description: Create a selection containing a collection of tags to perform subsequent operations on.
      operationId: CreateSelection
      parameters:
        - in: body
          name: selection
          description: The selection to create
          schema:
            $ref: '#/definitions/Selection'
          required: false
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Selection'
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        409:
          description: Duplicate selection
        default:
          $ref: '#/responses/Error'
    get:
      tags:
        - selections
      summary: Get all selections
      description: Get all selections.
      operationId: GetSelections
      parameters: []
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/Selection'
          description: Success
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}:
    parameters:
      - in: path
        name: id
        description: Selection ID
        type: string
        required: true
    put:
      tags:
        - selections
      summary: Update a selection
      description: Modify a selection
      operationId: UpdateSelection
      parameters:
        - in: body
          name: selection
          description: Selection to replace the existing selection with
          schema:
            $ref: '#/definitions/Selection'
          required: false
      responses:
        200:
          schema:
            $ref: '#/definitions/Selection'
          description: Success
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
    get:
      tags:
        - selections
      summary: Get a selection
      description: Get a selection's metadata.
      operationId: GetSelection
      responses:
        200:
          schema:
            $ref: '#/definitions/Selection'
          description: Success
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
    delete:
      tags:
        - selections
      summary: Delete a selection
      description: Delete a selection
      operationId: DeleteSelection
      responses:
        204:
          description: Successfully deleted
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
  /v2/selections/{id}/tags-with-values:
    get:
      tags:
        - selections
      summary: Get current values in a selection
      description: Get the current values and aggregates of the tags in a selection.
      operationId: GetSelectionTagsWithValues
      parameters:
        - in: path
          name: id
          description: The selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            $ref: '#/responses/GetTagsWithValuesResponse'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/tags:
    parameters:
    - in: path
      name: id
      description: Selection ID
      type: string
      required: true
    get:
      tags:
        - selections
      summary: Get the tags in a selection
      description: Get the metadata of the tags in a selection
      operationId: GetSelectionTags
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Tag'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
    delete:
      tags:
        - selections
      summary: Delete all of the tags in a selection
      description: Delete all of the tags in a seletion
      operationId: DeleteSelectionTags
      responses:
        204:
          description: Successfully deleted
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/values:
    get:
      tags:
        - selections
      summary: Get the values of the tags in a selection
      description: Get the current values of the tags in a given selection
      operationId: GetSelectionValues
      parameters:
        - in: path
          name: id
          description: Selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/TagPathWithCurrentAndAggregateValue'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/values/current:
    get:
      tags:
        - selections
      summary: Get the current values of the tags in a selection, including timestamps
      description: Get the current values of the tags in a selection, including timestamps
      operationId: GetSelectionCurrentTimestampedValues
      parameters:
        - in: path
          name: id
          description: Selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              description: Tag path with timestamped value
              type: object
              title: Tag Path With Current Value
              properties:
                path:
                  type: string
                  description: Tag path
                current:
                  $ref: '#/definitions/TagCurrentValue'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/values/current/value:
    get:
      tags:
        - selections
      summary: Get the current values of the tags in a selection, excluding timestamps
      description: Get the current values of the tags in a selection, excluding timestamps
      operationId: GetSelectionCurrentValues
      parameters:
        - in: path
          name: id
          description: Selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              description: Tag path with value
              type: object
              title: Tag Path With Value
              properties:
                path:
                  type: string
                  description: Tag path
                current:
                  $ref: '#/definitions/TagValue'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/values/current/timestamp:
    get:
      tags:
        - selections
      summary: Get the timestamps of the current values of the tags in a selection
      description: Get the timestamps of the current values of the tags in a selection
      operationId: GetSelectionValuesCurrentTimestamp
      parameters:
        - in: path
          name: id
          description: The selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            description: Array containing the paths of the tags in the selection, along with the timestamp of their current values.
            type: array
            title: Tag Paths With Timestamps
            items:
              type: object
              title: Tag Path and Timestamp
              description: A tag path and the timestamp of its current value
              properties:
                timestamp:
                  description: The current value's timestamp
                  type: string
                path:
                  description: The tag path
                  type: string
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/values/aggregates/min:
    get:
      tags:
        - selections
      summary: Get the "min" aggregate values for the tags in a selection
      description: Get the "min" aggregate values for the tags in a selection
      operationId: GetSelectionMinValues
      parameters:
        - in: path
          name: id
          description: The selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            description: Array containing the "min" values from the aggregates for each tag in the selection.
            type: array
            items:
              type: object
              title: Tag Paths and Count Values
              properties:
                path:
                  type: string
                min:
                  description: Minimum value from the tag's aggregates
                  type: number
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/values/aggregates/max:
    get:
      tags:
        - selections
      summary: Get the "max" aggregate values for the tags in a selection
      description: Get the "max" aggregate values for the tags in a selection
      operationId: GetSelectionMaxAggregates
      parameters:
        - in: path
          name: id
          description: Selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            description: Array containing the "max" values from the aggregates for each tag in the selection.
            type: array
            items:
              type: object
              title: Tag Path With Max Aggregate
              properties:
                path:
                  type: string
                max:
                  description: Maximum value from the tag's aggregates
                  type: number
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/values/aggregates/mean:
    get:
      tags:
        - selections
      summary: Get the "avg" aggregate values for the tags in a selection
      description: Get the "avg" aggregate values for the tags in a selection
      operationId: GetSelectionMeanValues
      parameters:
        - in: path
          name: id
          description: Selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            description: Array containing the "avg" values from the aggregates for each tag in the selection.
            type: array
            items:
              type: object
              title: Tag Path and Mean Value
              properties:
                path:
                  type: string
                mean:
                  description: Mean value from the tag's aggregates
                  type: number
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/values/aggregates/count:
    get:
      tags:
        - selections
      summary: Get the "count" aggregate values for the tags in a selection
      description: Get the "count" aggregate values for the tags in a selection
      operationId: GetSelectionCountValues
      parameters:
        - in: path
          name: id
          description: Selection ID
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            description: Array containing the "count" values from the aggregates for each tag in the selection.
            type: array
            items:
              type: object
              title: Tag Paths and Count Values
              properties:
                path:
                  type: string
                count:
                  description: Count value from the tag's aggregates
                  type: number
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID was not found
        default:
          $ref: '#/responses/Error'
  /v2/selections/{id}/reset-aggregates:
    post:
      tags:
        - selections
      summary: Reset the aggregates of all tags in a selection
      description: Reset the aggregates of all tags in a selection
      operationId: ResetSelectionAggregates
      parameters:
        - in: path
          name: id
          description: Selection ID
          type: string
          required: true
      responses:
        204:
          description: No Content
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Selection with the given ID not found
        default:
          $ref: '#/responses/Error'
  /v2/update-tags:
    post:
      tags:
        - tags
      summary: 'Create or update multiple tags'
      description: Create or update multiple tags in one request.
      operationId: CreateOrUpdateTags
      parameters:
        - in: body
          name: tagsAndMerge
          description: The tags to create or update, and a flag specifying whether keywords and properties should be merged for updates.
          schema:
            type: object
            title: Tag List and Merge Flag
            properties:
              tags:
                description: List of tags
                type: array
                items:
                  $ref: '#/definitions/Tag'
              merge:
                description: 'If set, performs a merge of any specified Keywords or Properties.'
                type: boolean
          required: true
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        409:
          description: 'Conflict: Type change not supported'
        default:
          $ref: '#/responses/Error'
  /v2/tags:
    post:
      tags:
        - tags
      summary: Create or update a tag
      description: Create or update single tag. Performs a merge of any specified Keywords or Properties. Changing a tag's type is not supported.
      operationId: CreateTag
      parameters:
        - in: body
          name: tags
          description: Tag to create
          schema:
            $ref: '#/definitions/Tag'
          required: true
      responses:
        201:
          description: 'Created: Tag created successfully'
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        409:
          description: 'Conflict: Type change not supported'
        default:
          $ref: '#/responses/Error'
    get:
      tags:
        - tags
      summary: Get multiple tags
      description: Get a list of tags, filtered based on the provided query parameters.
      operationId: GetTags
      parameters:
        - in: query
          name: path
          description: Comma-separated list of tag paths. May include glob-style wildcards
          type: string
          required: false
        - in: query
          name: keywords
          description: Comma-separated list of case-sensitive keywords.
          type: string
          required: false
        - in: query
          name: properties
          description: Comma-separated list of key/value property pairs.
          type: string
          required: false
        - in: query
          name: skip
          description: Used for pagination. Specifies the number of entries to skip in the response list. Typically used in combination with the take parameter.
          type: integer
          required: false
        - in: query
          name: take
          description: Used for pagination. Specfies the number of entries to include in the response list. Typically used in combination with the skip parameter.
          type: integer
          required: false
      responses:
        200:
          schema:
            $ref: '#/responses/GetTagsResponse'
          description: Success
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v2/tags-count:
    get:
      tags:
        - tags
      summary: Get the total number of tags
      description: Get a count of the total number of tags.
      operationId: GetTagCount
      parameters: []
      responses:
        200:
          description: Contains the number of tags
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v2/tags-with-values:
    get:
      tags:
        - tags
      summary: Get the current values of multiple tags
      responses:
        200:
          schema:
            $ref: '#/responses/GetTagsWithValuesResponse'
          description: Success
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        409:
          description: Conflict
        default:
          $ref: '#/responses/Error'
      description: 'Get a list of tags with their values in a single request, filtered based on the provided query parameters.'
      operationId: GetTagsWithValues
      parameters:
        - in: query
          name: path
          description: Comma-separated list of tag paths. May include glob-style wildcards.
          type: string
          required: false
        - in: query
          name: keywords
          description: Comma-separated list of case-sensitive keywords
          type: string
          required: false
        - in: query
          name: properties
          description: Comma-separated list of key/value property pairs
          type: string
          required: false
        - in: query
          name: skip
          description: Used for pagination. Specifies the number of entries to skip in the response list. Typically used in combination with the take parameter.
          type: integer
          required: false
        - in: query
          name: take
          description: Used for pagination. Specfies the number of entries to include in the response list. Typically used in combination with the skip parameter.
          type: integer
          required: false
  /v2/tags-with-values/{path}:
    get:
      tags:
        - tags
      summary: Get a tag and its current value
      description: Get a tag and its value
      operationId: GetTagWithValue
      parameters:
        - in: path
          name: path
          description: The tag path
          type: string
          required: true
      responses:
        200:
          schema:
            $ref: '#/definitions/TagWithValue'
          description: Success
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v2/tags/{path}:
    parameters:
      - in: path
        name: path
        description: Tag path
        type: string
        required: true
    put:
      tags:
        - tags
      summary: Create or replace a tag
      description: Replace the tag at the path, or create one if one doesn''t exist. A complete resource representation must be sent (no partial updates).
      operationId: CreateOrReplaceTag
      parameters:
        - in: body
          name: tag
          description: Tag to create or replace
          schema:
            $ref: '#/definitions/Tag'
          required: true
      responses:
        201:
          description: 'Created: Tag created successfully'
        204:
          description: 'No Content: Tag replaced successfully'
        401:
          $ref: '#/responses/Unauthorized'
        409:
          description: 'Conflict: Type change not supported'
    get:
      tags:
        - tags
      summary: Get a tag
      description: Get the metadata of a single tag.
      operationId: GetTag
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Tag'
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
    delete:
      tags:
        - tags
      summary: Delete a tag
      description: Deletes a tag
      operationId: DeleteTag
      responses:
        204:
          description: 'No content: Tag deleted successfully'
        404:
          description: Not Found
        default:
          $ref: '#/responses/Error'
  /v2/tags/{path}/values:
    get:
      tags:
        - tags
      summary: Get the aggregates and current value of a tag
      description: Get the current and aggregate values for the tag at the path.
      operationId: get-tag-values
      parameters:
        - in: path
          name: path
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/TagCurrentAndAggregateValue'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag not found
        default:
          $ref: '#/responses/Error'
  /v2/tags/{path}/values/current:
    parameters:
    - in: path
      name: path
      description: Tag path
      type: string
      required: true
    get:
      tags:
        - tags
      summary: Get the current value of a tag
      description: Get the current value of the tag at the path.
      operationId: get-tag-values-current
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/TagCurrentValue'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag not found
        default:
          $ref: '#/responses/Error'
    put:
      tags:
        - tags
      summary: Update the current value of a tag
      description: Update the current value of the tag at the path.
      operationId: UpdateTagCurrentValue
      responses:
        200:
          description: Tag Value Updated
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        409:
          description: Conflict
        default:
          $ref: '#/responses/Error'
      parameters:
        - in: body
          name: tagValue
          description: Timestamped value
          schema:
            $ref: '#/definitions/TagCurrentValue'
          required: true
  /v2/tags/{path}/values/current/timestamp:
    get:
      tags:
        - tags
      summary: Get the timestamp of a tag's current value
      description: Get tag most recent timestamp.
      operationId: get-tag-values-current-timestamp
      parameters:
        - in: path
          name: path
          description: Tag path
          type: string
          required: true
      responses:
        200:
          description: Timestamp
        204:
          description: No timestamped value found
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag not found
        default:
          $ref: '#/responses/Error'
  /v2/tags/{path}/values/current/value:
    get:
      tags:
        - tags
      summary: Get the current value of a tag without its timestamp
      description: Get the current value of a tag
      operationId: GetTagCurrentValue
      parameters:
        - in: path
          name: path
          description: Tag path
          type: string
          required: true
      responses:
        200:
          schema:
            $ref: '#/definitions/TagValue'
          description: Success
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag not found
        default:
          $ref: '#/responses/Error'
  /v2/tags/{path}/values/aggregates/min:
    get:
      tags:
        - tagAggregates
      summary: Get the value of a tag's "min" aggregate
      description: Get the value of a tag's "min" aggregate
      operationId: GetTagMinimum
      parameters:
        - in: path
          name: path
          description: Tag path
          type: string
          required: true
      responses:
        200:
          description: Minimum aggregate value
          schema:
            type: string
        204:
          description: No aggregate value found
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag with the given path not found
        default:
          $ref: '#/responses/Error'
  /v2/tags/{path}/values/aggregates/max:
    get:
      tags:
        - tagAggregates
      summary: Get the value of a tag's "max" aggregate
      description: Get the value of a tag's "max" aggregate
      operationId: GetTagMaxAggregate
      responses:
        200:
          description: Maximum aggregate value
          schema:
            type: string
        204:
          description: No aggregate value found
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag with the given path was not found
        default:
          $ref: '#/responses/Error'
      parameters:
        - in: path
          name: path
          description: Tag path
          type: string
          required: true
  /v2/tags/{path}/values/aggregates/mean:
    get:
      tags:
        - tagAggregates
      summary: Get the value of a tag's "avg" aggregate
      description: Get the value of a tag's "avg" aggregate
      operationId: GetTagMeanAggregate
      responses:
        200:
          description: Mean aggregate value
          schema:
            type: string
        204:
          description: No aggregate value found
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag with the given path was not found
        default:
          $ref: '#/responses/Error'
      parameters:
        - in: path
          name: path
          description: Tag path
          type: string
          required: true
  /v2/tags/{path}/values/aggregates/count:
    get:
      tags:
        - tagAggregates
      summary: Get the value of a tag's "count" aggregate
      description: Get the value of a tag's "count" aggregate
      operationId: GetTagCountAggregate
      parameters:
        - in: path
          name: path
          description: Tag path
          type: string
          required: true
      responses:
        200:
          description: Count aggregate value
          schema:
            type: string
        204:
          description: No aggregate value found
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag with the given path was not found
        default:
          $ref: '#/responses/Error'
  /v2/tags/{path}/reset-aggregates:
    post:
      tags:
        - tagAggregates
      summary: 'Reset the aggregates of a tag'
      description: Reset tag aggregates
      operationId: ResetTagAggregates
      parameters:
        - in: path
          name: path
          description: Tag path
          type: string
          required: true
      responses:
        200:
          description: Success
        401:
          $ref: '#/responses/Unauthorized'
        404:
          description: Tag with the given path was not found
        default:
          $ref: '#/responses/Error'
  /v1/tags-rpc/update-current-values:
    post:
      tags:
        - tags
      summary: Update the current values of multiple tags
      description: Push multiple current value updates to multiple tags in one request. Note that this route is deprecated.
      operationId: RpcUpdateTagCurrentValues
      parameters:
        - in: body
          name: updates
          description: Updates
          schema:
            type: array
            items:
              $ref: '#/definitions/TagUpdate'
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v2/update-current-values:
    post:
      tags:
        - tags
      summary: Update the current values of multiple tags (SystemLink Server only)
      description: Push multiple current value updates to multiple tags in one request.
      operationId: UpdateTagCurrentValues
      parameters:
        - in: body
          name: updates
          description: Updates
          schema:
            type: array
            items:
              $ref: '#/definitions/TagUpdate'
      responses:
        200:
          description: Success
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        default:
          $ref: '#/responses/Error'
  /v2/tags/{path}/update-values:
    post:
      tags:
        - tags
      summary: Send multiple value updates to a tag
      description: Push a list of current value update objects to update the value of the tag at the path multiple times. This can be used to send value history in bulk.
      operationId: update-tag-values
      responses:
        200:
          description: Tag Values Updated
        400:
          description: Bad Request
        401:
          $ref: '#/responses/Unauthorized'
        409:
          description: Conflict
        default:
          $ref: '#/responses/Error'
      parameters:
        - in: path
          name: path
          description: Tag path
          type: string
          required: true
        - in: body
          name: tagValues
          description: Timestamped values
          schema:
            type: array
            items:
              $ref: '#/definitions/TagCurrentValue'
          required: true

definitions:
  Error:
    description: Contains error information
    type: object
    properties:
      name:
        description: String error code
        type: string
      code:
        description: Numeric error code
        type: integer
      resourceType:
        description: Type of resource associated with the error
        type: string
      resourceId:
        description: Identifier of the resource associated with the error
        type: string
      message:
        description: Complete error message
        type: string
      args:
        description: Positional argument values for the error code
        type: array
        items:
          type: string
      innerErrors:
        type: array
        items:
          $ref: '#/definitions/Error'
    example:
      name: Tag.NoSuchTag
      code: -251909
      resourceType:
      resourceId:
      message: "No such tag: 'foo'"
      args: ['foo']
  TagType:
    type: string
    title: Tag Data Type
    enum: &TYPES [DOUBLE, INT, STRING, BOOLEAN, U_INT64, DATE_TIME]
  TagWithValue:
    description: A tag and its current value
    type: object
    title: Tag With Value
    properties:
      tag:
        $ref: '#/definitions/Tag'
      current:
        $ref: '#/definitions/TagCurrentValue'
      aggregates:
        $ref: '#/definitions/TagAggregates'
    example:
      tag:
        path: foo
        type: DOUBLE
        keywords: [fooKeyword, barKeyword]
      current:
        value:
          type: DOUBLE
          value: 3.14
        timestamp: '2018-09-04T18:45:08.540Z'
      aggregates:
        sum: 10.5
        min: 0.0
        max: 5.0
        mean: 2.0
        count: 5
  TagValue:
    description: Value of a tag
    type: object
    title: Tag Value
    properties:
      value:
        type: string
      type:
        type: string
        enum: *TYPES
    example:
      type: DOUBLE
      value: 3.14
  TagPathWithCurrentAndAggregateValue:
    description: Tag path with its current value and aggregates
    type: object
    title: Tag Path Current And Aggregate Value
    properties:
      path:
        type: string
      current:
        $ref: '#/definitions/TagCurrentValue'
      aggregates:
        $ref: '#/definitions/TagAggregates'
    example:
      path: foo
      current:
        value:
          type: DOUBLE
          value: 3.14
      aggregates:
        sum: 10.5
        min: 0.0
        max: 5.0
        mean: 2.0
        count: 5
  TagCurrentValue:
    description: Current value of a tag
    type: object
    title: Tag Current Value
    properties:
      value:
        $ref: '#/definitions/TagValue'
      timestamp:
        description: Timestamp associated with the value
        type: string
        format: date-time
    example:
      value:
        type: DOUBLE
        value: 3.14
      timestamp: '2018-09-04T18:45:08.540Z'
  TagCurrentAndAggregateValue:
    type: object
    title: Tag Current And Aggregate Value
    properties:
      current:
        $ref: '#/definitions/TagCurrentValue'
      aggregates:
        $ref: '#/definitions/TagAggregates'
    example:
      current:
        value:
          type: DOUBLE
          value: 3.14
        timestamp: '2018-09-04T18:45:08.540Z'
      aggregates:
        sum: 10.5
        min: 0.0
        max: 5.0
        mean: 2.0
        count: 5
  TagAggregates:
    description: Aggregate values of a tag
    type: object
    title: Tag Aggregate Value
    properties:
      sum:
        description: Sum aggregate value
        type: number
      min:
        description: Minimum aggregate value
        type: number
      max:
        description: Maximum aggregate value
        type: number
      count:
        description: Count aggregate value
        type: integer
      avg:
        description: Average aggregate value
        type: number
    example:
      sum: 10.5
      min: 0.0
      max: 5.0
      mean: 2.0
      count: 5
  Tag:
    description: Object containing a tag's metadata, excluding current and aggregate values
    type: object
    title: Tag
    properties:
      type:
        description: Type
        type: string
        enum: *TYPES
      properties:
        type: object
      path:
        type: string
      keywords:
        type: array
        items:
          type: string
      collectAggregates:
        type: boolean
    example:
      type: DOUBLE
      properties:
        key1: value1
        key2: value2
      path: foo
      keywords: [fooKeyword, barKeyword]
      collectAggregates: true
  TagUpdate:
    description: Object containing a tag's path, and one or more updates to be applied to it
    type: object
    title: Tag Update
    properties:
      path:
        type: string
      updates:
        type: array
        items:
          $ref: '$/definitions/TagCurrentValue'
    example:
      path: foo
      updates:
        - value:
            type: DOUBLE
            value: 3.14
          timestamp: '2018-09-04T18:45:08.540Z'
        - value:
            type: DOUBLE
            value: 5.0
          timestamp: '2018-09-04T18:45:09.540Z'
  SubscriptionUpdate:
    description: Updates for a subscriptions
    type: object
    title: Subscription Update
    properties:
      updates:
        type: array
        items:
          $ref: '#/definitions/SubscriptionTagUpdate'
      subscriptionId:
        type: string
      nonexistentTags:
        description: List of tags which did not exist
        type: array
        items:
          type: string
      deletedTags:
        description: List of tags which have been deleted
        type: array
        items:
          type: string
      createdTags:
        description: List of tags which have been created
        type: array
        items:
          type: string
      alias:
        description: Name of the subscription
        type: string
  SubscriptionTagUpdate:
    description: Update details for a tag subscription
    type: object
    title: Subscription Tag Update
    properties:
      value:
        description: Updated tag value
        type: string
      type:
        type: string
        enum: *TYPES
      timestamp:
        description: Updated timestamp
        type: string
      tag:
        $ref: '#/definitions/Tag'
      aggregates:
        $ref: '#/definitions/TagAggregates'
    example:
      value: 5.0
      type: DOUBLE
      timestamp: '2018-09-04T18:45:08.540Z'
      tag:
        type: DOUBLE
        properties:
          key1: value1
          key2: value2
        path: foo
        keywords: [fooKeyword, barKeyword]
      aggregates:
        sum: 10.5
        min: 0.0
        max: 5.0
        mean: 2.0
        count: 5
  Subscription:
    description: Object describing a subscription's metadata
    type: object
    title: Subscription
    properties:
      updatesOnly:
        description: Whether to notify only about updates
        type: boolean
      tags:
        description: List of subscribed tag paths
        type: array
        items:
          type: string
      alias:
        description: Name of the subscription
        type: string
    example:
      updatesOnly: true
      tags: [tag1, tag2, tag3]
      alias: foo
  Selection:
    description: Object describing a selection's metadata
    type: object
    title: Selection
    required:
      - searchPaths
    properties:
      searchPaths:
        type: array
        items:
          type: string
      inactivityTimeout:
        description: Inactivity timeout in seconds
        type: integer
        maximum: 900
      id:
        type: string
    example:
      searchPaths: [tag1, tag2, tag3]
      inactivityTimeout: 1000
      id: 22520497-e85b-427f-980c-ca328fc72f75
